"""empty message

Revision ID: 75b057213664
Revises: 2da2c0ccb068
Create Date: 2023-12-12 15:36:04.508285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b057213664'
down_revision = '2da2c0ccb068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletters', 'published_at')
    op.drop_column('newsletters', 'edited_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('edited_at', sa.DATETIME(), nullable=True))
    op.add_column('newsletters', sa.Column('published_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###
